services:
  scraper-api:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: scraper-container
    volumes:
      - .:/app  # Host Directory : Container Directory
    depends_on:
      - mongodb
    networks:
      - internal_network
    env_file:
      - .env.prod
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 5
    command: ["sh", "-c", "sleep 10 && uvicorn main:app --host 0.0.0.0 --port 8000"]

  tor:
    build:
      context: .
      dockerfile: Dockerfile.tor
    container_name: tor
    depends_on:
      - scraper-api
    networks:
      - internal_network
    volumes:
      - tor_data:/var/lib/tor
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - internal_network
    ports:
      - "27028:27017"  # Host Port : Container Port

networks:
  internal_network:

volumes:
  mongo_data:
  tor_data:
