version: '3.8'

services:
  scraper-api:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: scraper-container
    depends_on:
      - mongodb
    networks:
      - internal_network
    env_file:
      - .env.prod
    restart: unless-stopped

  tor:
    build:
      context: .
      dockerfile: Dockerfile.tor
    container_name: tor
    depends_on:
      - scraper-api
    networks:
      - internal_network
    volumes:
      - tor_data:/var/lib/tor
    restart: unless-stopped

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - internal_network

networks:
  internal_network:

volumes:
  mongo_data:
  tor_data:
